RedisExchangeAPIApp.Web/Models/ErrorViewModel.cs
namespace RedisExchangeAPIApp.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisExchangeAPIApp.Web/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPIApp.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeAPIApp.Web.Controllers
{
    public class HashTypeController : Controller
    {
        private readonly RedisService _rediceService;
        private readonly IDatabase _db;
        private string hashKey = "hashdicnames";
        public HashTypeController(RedisService rediceService)
        {
            _rediceService = rediceService;
            _db = _rediceService.GetDb(3);
        }


        public IActionResult Index()
        {
            Dictionary<string,string> list = new Dictionary<string,string>();
            if(_db.KeyExists(hashKey))
            {
                _db.HashGetAll(hashKey).ToList().ForEach(x=>
                {
                    list.Add(x.Name, x.Value);
                });
            }


            return View(list);
        }

        [HttpPost]
        public IActionResult Add(string name, string val)
        {
            _db.HashSet(hashKey, name, val);

            return RedirectToAction("Index");
        }
        public IActionResult DeleteItem(string name)
        {
            _db.HashDelete(hashKey, name);

            return RedirectToAction("Index");
        }
    }
}

RedisExchangeAPIApp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPIApp.Web.Models;
using System.Diagnostics;

namespace RedisExchangeAPIApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisExchangeAPIApp.Web/Controllers/ListTypesController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPIApp.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeAPIApp.Web.Controllers
{
    public class ListTypesController : Controller
    {

        private readonly RedisService _rediceService;
        private readonly IDatabase _db;
        private string listKey = "names";

        public ListTypesController(RedisService rediceService)
        {
            _rediceService = rediceService;
            _db = _rediceService.GetDb(0);
        }

        public IActionResult Index()
        {
            List<string> namelist = new List<string>();
            if(_db.KeyExists(listKey))
            {
                _db.ListRange(listKey).ToList().ForEach(x =>
                {
                    namelist.Add(x.ToString());
                });
            }
            return View(namelist);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            _db.ListRightPush(listKey, name);


            return RedirectToAction("Index");
        }
        public IActionResult DeleteItem(string name)
        {
            _db.ListRemoveAsync(listKey, name).Wait();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteFirstItem()
        {
            _db.ListLeftPop(listKey);
            return RedirectToAction("Index");
        }
    }
}

RedisExchangeAPIApp.Web/Controllers/SetTypesController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPIApp.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeAPIApp.Web.Controllers
{
    public class SetTypesController : Controller
    {

        private readonly RedisService _rediceService;
        private readonly IDatabase _db;
        private string listKey = "names";

        //Sliding expiration yok ama timeout ile bu özelliği kazandırabiliyoruz
        public SetTypesController(RedisService rediceService)
        {
            _rediceService = rediceService;
            _db = _rediceService.GetDb(1);
        }

        public IActionResult Index()
        {
            HashSet<string> nameList = new HashSet<string>();
            if (_db.KeyExists(listKey))
            {
                _db.SetMembers(listKey).ToList().ForEach(x =>
                {
                    nameList.Add(x.ToString());
                });
            }
            return View(nameList);
        }


        [HttpPost]
        public IActionResult Add(string name)
        {
            //if(!_db.KeyExists(listKey)) Sliding özelliği vermek için kullanabiliriz
            //{
                _db.KeyExpire(listKey, DateTime.Now.AddMinutes(5));
            //}
            _db.SetAdd(listKey, name);


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteItem(string name)
        {
            await _db.SetRemoveAsync(listKey, name);
            return RedirectToAction("Index");
        }
    }
}

RedisExchangeAPIApp.Web/Controllers/SortedSetsController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPIApp.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeAPIApp.Web.Controllers
{
    public class SortedSetsController : Controller
    {
        private readonly RedisService _rediceService;
        private readonly IDatabase _db;
        private string listKey = "sortedsetnames";
        public SortedSetsController(RedisService rediceService)
        {
            _rediceService = rediceService;
            _db = _rediceService.GetDb(2);
        }
        public IActionResult Index()
        {
            HashSet<string> list = new HashSet<string>();

            if(_db.KeyExists(listKey))
            {
                //DB deki hali ile sıralama/ score değeri geliyor
                //_db.SortedSetScan(listKey).ToList().ForEach(x =>
                //{
                //    list.Add(x.ToString());
                //});
                //büyükten küçüğe sıralama /  score değeri gelmiyor
                _db.SortedSetRangeByRank(listKey, order: Order.Descending).ToList().ForEach(x => 
                {
                    list.Add(x.ToString());
                });
            }
            return View(list);
        }
        [HttpPost]
        public IActionResult Add(string name,int score)
        {
            _db.SortedSetAdd(listKey,name,score);

            _db.KeyExpire(listKey, DateTime.Now.AddMinutes(1));

            return RedirectToAction("Index");
        }
        public IActionResult DeleteItem(string name)
        {
            _db.SortedSetRemove(listKey,name);

            return RedirectToAction("Index");
        }
    }
}

RedisExchangeAPIApp.Web/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPIApp.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeAPIApp.Web.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _rediceService;
        private readonly IDatabase _db;

        public StringTypeController(RedisService rediceService)
        {
            _rediceService = rediceService;
            _db = _rediceService.GetDb(0);
        }
        public IActionResult Index()
        {
            _db.StringSet("name", "Berfim Korkmaz");
            _db.StringSet("ziyaretci", 100);
            return View();
        }
        public IActionResult ShowStringType()
        {
            //ASYNC METOT
            //_db.StringIncrement("ziyaretci", 100);
            //var result = _db.StringIncrementAsync("ziyaretci", 100).Result; Sonuç lazım ise 
            //_db.StringIncrementAsync("ziyaretci",100).Wait(); // Sadece bu metodu asenkron bir şekilde yap

            //GET
            //var nameval = _db.StringGet("name");
            //var ziyval = _db.StringGet("ziyaretci");
            //if (nameval.HasValue)
            //{
            //    ViewBag.nameval = nameval;
            //    ViewBag.ziyval = ziyval;
            //}
            //RANGE
            //var rangevalue = _db.StringGetRange("name", 0, 6);
            //if (rangevalue.HasValue)
            //{
            //    ViewBag.rangevalue = rangevalue;
            //}  
            
            //LENGTH
            var lengthvalue = _db.StringLength("name");
            ViewBag.lengthvalue = lengthvalue;

            return View();
        }
    }
}

RedisExchangeAPIApp.Web/Views/HashType/Index.cshtml
@model Dictionary<string,string>


<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">

    <input type="text" name="name" />
    <input type="text" name="val" />
    <button type="submit">Kaydet</button>
</form>
@foreach (var item in Model)
{
    <h2>@item.Key -> @item.Value  <a type="submit" asp-route-name="@item.Key" asp-action="DeleteItem" asp-controller="HashType">Sil</a> </h2>
}

RedisExchangeAPIApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RedisExchangeAPIApp.Web/Views/ListTypes/Index.cshtml
@model List<string>


<h2>Baştan sil  <a type="submit" asp-action="DeleteFirstItem" asp-controller="ListTypes">Sil</a> </h2>

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">

    <input type="text" name="name"/>
    <button type="submit">Kaydet</button>
</form>
@foreach (var item in Model)
{
    <h2>@item  <a type="submit" asp-route-name="@item" asp-action="DeleteItem" asp-controller="ListTypes">Sil</a> </h2>
}

RedisExchangeAPIApp.Web/Views/SetTypes/Index.cshtml
@model HashSet<string>


<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">

    <input type="text" name="name" />
    <button type="submit">Kaydet</button>
</form>
@foreach (var item in Model)
{
    <h2>@item  <a type="submit" asp-route-name="@item" asp-action="DeleteItem" asp-controller="SetTypes">Sil</a> </h2>
}

RedisExchangeAPIApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeAPIApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeAPIApp.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeAPIApp.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StringType" asp-action="Index">StringType</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StringType" asp-action="ShowStringType">ShowStringType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListTypes" asp-action="Index">ListTypesIndex</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SetTypes" asp-action="Index">SetTypesIndex</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SortedSets" asp-action="Index">SortedSetsTypesIndex</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HashType" asp-action="Index">HashTypeIndex</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RedisExchangeAPIApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RedisExchangeAPIApp.Web/Views/SortedSets/Index.cshtml
@model HashSet<string>


<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">

    <input type="text" name="name" />
    <input type="number" name="score" />
    <button type="submit">Kaydet</button>
</form>
@foreach (var item in Model)
{
    <h2>@item  <a type="submit" asp-route-name="@item" asp-action="DeleteItem" asp-controller="SortedSets">Sil</a> </h2>
}

RedisExchangeAPIApp.Web/Views/StringType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RedisExchangeAPIApp.Web/Views/StringType/ShowStringType.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@* <h2>@ViewBag.nameval</h2>
<h2>@ViewBag.ziyval</h2> *@
@* <h1>@ViewBag.rangevalue</h1> *@
<h1>@ViewBag.lengthvalue</h1>